version: '3.8'

services:
  label-studio:
    image: systonami/custom_label_studio:tagname
    container_name: custom-label-studio-container
    environment:
      - LABEL_STUDIO_USERNAME=${LABEL_STUDIO_USERNAME}
      - LABEL_STUDIO_PASSWORD=${LABEL_STUDIO_PASSWORD}
      - LABEL_STUDIO_API_KEY=${LABEL_STUDIO_API_KEY}
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
      - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=${LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT}
    volumes:
      - ${DATA_VOLUME_PATH}:${LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT}/${DATA_DIR}
      - ./data:${LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT}
    ports:
      - "8080:8080"
    networks:
      - labelstudio-network
    healthcheck:
      test: ["CMD", "curl", "-f", "${LABEL_STUDIO_URL}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  storage-manager:
    build: .
    environment:
      - LABEL_STUDIO_URL=${LABEL_STUDIO_URL}
      - DATA_DIR=${DATA_DIR}
      - DATA_VOLUME_PATH=${DATA_VOLUME_PATH}
    volumes:
      - ${DATA_VOLUME_PATH}:${LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT}/${DATA_DIR}
    depends_on:
      label-studio:
        condition: service_healthy
    networks:
      - labelstudio-network
    restart: on-failure

networks:
  labelstudio-network:

volumes:
  postgres_data:
